from datetime import datetime, timedelta, timezone

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from models import Asset


SEEDED_ASSETS = [
    {
        "title": "Auth_Middleware_V2.ts",
        "description": "Protokol keamanan untuk sistem autentikasi dan route guard tim.",
        "asset_type": "script",
        "category": "Security",
        "owner_handle": "JD",
        "size_bytes": 180_224,
        "file_extension": "ts",
        "badge": "TypeScript",
        "tone": "primary",
        "preview_style": "code",
        "status": "synced",
        "is_private": True,
        "days_ago": 0,
    },
    {
        "title": "Hero_Concept_Final.png",
        "description": "Aset visual untuk landing page dan presentasi identitas project.",
        "asset_type": "image",
        "category": "Concept Art",
        "owner_handle": "AS",
        "size_bytes": 2_450_000,
        "file_extension": "png",
        "badge": "PNG • 4K",
        "tone": "secondary",
        "preview_style": "waves",
        "status": "processing",
        "is_private": False,
        "days_ago": 1,
    },
    {
        "title": "Ambient_Engine_01.wav",
        "description": "Efek suara latar untuk transisi UI dan preview dashboard.",
        "asset_type": "audio",
        "category": "Audio",
        "owner_handle": "ML",
        "size_bytes": 621_000,
        "file_extension": "wav",
        "badge": "WAV • HQ",
        "tone": "tertiary",
        "preview_style": "bars",
        "status": "synced",
        "is_private": True,
        "days_ago": 2,
    },
    {
        "title": "App_Config_Production.json",
        "description": "Pengaturan variabel lingkungan dan policy deployment produksi.",
        "asset_type": "config",
        "category": "Deployment",
        "owner_handle": "JD",
        "size_bytes": 12_000,
        "file_extension": "json",
        "badge": "JSON",
        "tone": "warm",
        "preview_style": "database",
        "status": "synced",
        "is_private": True,
        "days_ago": 3,
    },
    {
        "title": "Inventory_Service.py",
        "description": "Service layer untuk sinkronisasi inventory aset dan tagging internal.",
        "asset_type": "script",
        "category": "Backend",
        "owner_handle": "RK",
        "size_bytes": 214_000,
        "file_extension": "py",
        "badge": "Python",
        "tone": "primary",
        "preview_style": "code",
        "status": "synced",
        "is_private": True,
        "days_ago": 5,
    },
    {
        "title": "Dialogue_Bank_v12.md",
        "description": "Dokumentasi voice direction dan branching untuk adegan utama.",
        "asset_type": "document",
        "category": "Narrative",
        "owner_handle": "AS",
        "size_bytes": 96_000,
        "file_extension": "md",
        "badge": "Markdown",
        "tone": "primary",
        "preview_style": "code",
        "status": "synced",
        "is_private": False,
        "days_ago": 8,
    },
    {
        "title": "HUD_Redesign_Export.zip",
        "description": "Bundle ekspor UI HUD final dari Figma dan motion specs.",
        "asset_type": "bundle",
        "category": "UI/UX",
        "owner_handle": "ML",
        "size_bytes": 1_920_000,
        "file_extension": "zip",
        "badge": "ZIP",
        "tone": "secondary",
        "preview_style": "waves",
        "status": "queued",
        "is_private": True,
        "days_ago": 13,
    },
    {
        "title": "Boss_VO_Take_07.wav",
        "description": "Final voice take untuk boss introduction sequence.",
        "asset_type": "audio",
        "category": "Voice Over",
        "owner_handle": "TR",
        "size_bytes": 855_000,
        "file_extension": "wav",
        "badge": "WAV",
        "tone": "tertiary",
        "preview_style": "bars",
        "status": "synced",
        "is_private": True,
        "days_ago": 21,
    },
    {
        "title": "StateMachine_EnemyAI.cs",
        "description": "Skrip state machine untuk perilaku musuh dan transisi serangan.",
        "asset_type": "script",
        "category": "Gameplay",
        "owner_handle": "JD",
        "size_bytes": 310_000,
        "file_extension": "cs",
        "badge": "C#",
        "tone": "primary",
        "preview_style": "code",
        "status": "synced",
        "is_private": True,
        "days_ago": 34,
    },
    {
        "title": "Quest_Flow_Whiteboard.png",
        "description": "Diagram alur quest utama untuk sinkronisasi desain dan implementasi.",
        "asset_type": "image",
        "category": "Design",
        "owner_handle": "RK",
        "size_bytes": 1_120_000,
        "file_extension": "png",
        "badge": "PNG",
        "tone": "secondary",
        "preview_style": "waves",
        "status": "processing",
        "is_private": False,
        "days_ago": 55,
    },
    {
        "title": "Release_Checklist_Q3.md",
        "description": "Checklist deployment, backup, dan rollback untuk milestone berikutnya.",
        "asset_type": "document",
        "category": "Operations",
        "owner_handle": "ML",
        "size_bytes": 42_000,
        "file_extension": "md",
        "badge": "Markdown",
        "tone": "primary",
        "preview_style": "code",
        "status": "synced",
        "is_private": True,
        "days_ago": 89,
    },
    {
        "title": "Patch_Notes_Draft.txt",
        "description": "Draft catatan perubahan untuk build internal QA.",
        "asset_type": "document",
        "category": "QA",
        "owner_handle": "TR",
        "size_bytes": 18_000,
        "file_extension": "txt",
        "badge": "TXT",
        "tone": "warm",
        "preview_style": "database",
        "status": "queued",
        "is_private": True,
        "days_ago": 144,
    },
]


def seed_database(session: Session) -> None:
    existing_count = session.scalar(select(func.count()).select_from(Asset))
    if existing_count:
        return

    now = datetime.now(timezone.utc)
    assets = []
    for item in SEEDED_ASSETS:
        created_at = now - timedelta(days=item["days_ago"])
        assets.append(
            Asset(
                title=item["title"],
                description=item["description"],
                asset_type=item["asset_type"],
                category=item["category"],
                owner_handle=item["owner_handle"],
                size_bytes=item["size_bytes"],
                file_extension=item["file_extension"],
                badge=item["badge"],
                tone=item["tone"],
                preview_style=item["preview_style"],
                status=item["status"],
                is_private=item["is_private"],
                created_at=created_at,
                updated_at=created_at,
            )
        )

    session.add_all(assets)
    session.commit()
